### ISSUE TITLE
spirv_tools::Optimizer produces invalid output (no instructions), but CLI works

### ISSUE THREAD

**Issue by Boscop** [EmbarkStudios/spirv-tools-rs#10]
**Describe the bug**
When using spirv-opt as a crate, validation of its output fails, whereas with the CLI it succeeds.

(Maybe related to issue https://github.com/EmbarkStudios/spirv-tools-rs/issues/8)

**To Reproduce**
1. Run this function on the attached module `minimal.spv`:
```rust
// const TARGET_ENV: Option<TargetEnv> = Some(TargetEnv::OpenGL_4_3);
const TARGET_ENV: Option<TargetEnv> = None;

fn do_spirv_opt(spv_binary: &[u32]) -> Vec<u32> {
	use spirv_tools::{
		error,
		opt::{self, Optimizer},
	};

	let mut optimizer = opt::create(TARGET_ENV);

	optimizer
		// .register_size_passes()
		.register_performance_passes()
		.register_pass(opt::Passes::EliminateDeadConstant)
		.register_pass(opt::Passes::StripDebugInfo);

	let result = optimizer.optimize(
		&spv_binary,
		&mut |msg: error::Message| {
			eprintln!("[{:?}] {}", msg.level, msg.message);
		},
		None,
	);

	match result {
		Ok(binary) => {
			let r = Vec::from(binary.as_ref());
			println!("opt size: {}", r.len());
			r
		}
		Err(e) => {
			eprintln!("spirv-opt failed, leaving as unoptimized: {}", e);
			spv_binary.to_vec()
		}
	}
}
```
2. Then validate it, by calling:
```rust
fn do_spirv_val(spv_binary: &[u32]) {
	use spirv_tools::val::{self, Validator};

	let validator = val::create(TARGET_ENV);

	if let Err(e) = validator.validate(spv_binary, None) {
		eprintln!("spirv-val failed: {}", e);
	}
}
```

3. See error:
> spirv-val failed: invalid binary:0:0 - Invalid instruction word count: 0

**Expected behavior**
Same output as CLI.

**Device:**
 - OS: Manjaro

**Additional context**
I attached a zip that contains the original file (minimal.spv), the one optimized with this crate (minimal-opt-crate.spv) and the one optimized with the spirv-opt CLI (minimal-opt-cli.spv) as well as their disassembled versions as txt files.

[spv.zip](https://github.com/EmbarkStudios/spirv-tools-rs/files/5685767/spv.zip)

**Comment by Jake-Shadle** [comment]
This was fixed already in #9 , I just haven't made a release yet, I'll close this issue when I do.

**Comment by Boscop** [comment]
@Jake-Shadle I tried the latest version 0.2 as well as the latest git `main` branch.
It's weird, I still get the error:
With `spirv-tools = "0.2"` I get an empty spv file and:
> spirv-val failed: invalid binary:0:0 - Invalid SPIR-V magic number.

so the same as issue #8.

With `spirv-tools = { git = "https://github.com/EmbarkStudios/spirv-tools-rs", branch = "main" }` I get:
> spirv-val failed: invalid binary:0:0 - Invalid instruction word count: 0

The resulting spv file has a size of 876 bytes, but no instructions.

Could this be causing it?:
`spirv-builder = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "c1dc273" }`
So I have two versions of spirv-tools in Cargo.lock. But I'm not calling the one imported by `spirv-builder`.

**Comment by Jake-Shadle** [comment]
Ugh, looking into it.
